export const DocsData = [
    {
      doctor_id: 1,
      name: "Dr. John Doe",
      NPI_Number: " ",
      username: "",
      doctore_Type: "",
      sales_rep: "",
      admin: false,
    },
    {
      doctor_id: 2,
      name: "Dr. Luvis",
      NPI_Number: "734753487587",
      username: "LV123",
      doctore_Type: "eye",
      sales_rep: " interpretiting doctor",
      admin: false,
    },
    {
      doctor_id: 3,
      name: "Dr. Doe",
      NPI_Number: "734757777587",
      username: "uu123",
      doctore_Type: "eye",
      sales_rep: " interpretiting doctor",
      admin: true,
    },
    {
      doctor_id: 4,
      name: "Dr. Mary",
      NPI_Number: "734722222587",
      username: "OO23",
      doctore_Type: "eye",
      sales_rep: " interpretiting doctor",
      admin: false,
    },
    {
      doctor_id: 5,
      name: "Dr. Mark",
      NPI_Number: "734753444487",
      username: "MM3",
      doctore_Type: "eye",
      sales_rep: " interpretiting doctor",
      admin: false,
    },
    {
      doctor_id: 6,
      name: "Dr. Geny",
      NPI_Number: "7347500587",
      username: "GG3",
      doctore_Type: "eye",
      sales_rep: " interpretiting doctor",
      admin: true,
    },
    {
      doctor_id: 7,
      name: "Dr. Godwin",
      NPI_Number: "734722227587",
      username: "WW1",
      doctore_Type: "eye",
      sales_rep: " interpretiting doctor",
      admin: false,
    },
    {
      doctor_id: 8,
      name: "Dr. Frank",
      NPI_Number: "734799997587",
      username: "FW1",
      doctore_Type: "eye",
      sales_rep: " interpretiting doctor",
      admin: false,
    },
    {
      doctor_id: 9,
      name: "Dr. Williams",
      NPI_Number: "731111227587",
      username: "DW1",
      doctore_Type: "eye",
      sales_rep: " interpretiting doctor",
      admin: false,
    },
  ];